name: NuGet Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1          
      - name: Build solution and generate NuGet package
        run: |  
          cd ../SlaytonNichols.Common
          dotnet pack -c Release -o out  
          dotnet nuget add source --username SlaytonNichols --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/SlaytonNichols/index.json"

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ../SlaytonNichols.Common/out/*.nupkg --skip-duplicate --no-symbols true --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"